# Generated by Django 3.2.5 on 2024-05-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_comuna_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.region'),
        ),
    ]
